---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: 8-demo-image-policy-flux
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: 8-demo-repo-flux
  policy:
    semver:
      range: 7.8.x
