---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: 8-demo-repo-flux
  namespace: flux-system
spec:
  image: docker.io/eafolabi/8-demo-flux
  interval: 5m0s
  secretRef:
    name: docker-auth
