---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 8-demo-kustomize
  namespace: flux-system
spec:
  interval: 1m40s
  path: ./manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: 8-demo-flux
  targetNamespace: 8-demo
