---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: 8-demo-flux
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: 8-demo
  secretRef:
    name: 8-demo-git-auth
  url: ssh://git@github.com/eafolabi/flux-demo.git
