---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: suspend-kustomize
  namespace: flux-system
spec:
  interval: 1m40s
  path: ./
  prune: true
  sourceRef:
    kind: OCIRepository
    name: suspend
  healthChecks:
    - apiVersion: source.toolkit.fluxcd.io/v1beta2
      kind: OCIRepository
      namespace: flux-system 
      name: oci-suspend
  timeout: 60s    
