---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: suspend-kustomize
  namespace: flux-system
spec:
  interval: 1m40s
  path: ./
  prune: true
  sourceRef:
    kind: OCIRepository
    name: suspend
