---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 7-demo-kustomize-v2
  namespace: flux-system
spec:
  dependsOn:
  - name: infra-db-kustomize
  healthChecks:
  - kind: Deployment
    name: block-buster-7-7-0
    namespace: 7-demo
  interval: 10s
  path: ./
  prune: true
  sourceRef:
    kind: OCIRepository
    name: 7-demo-oci-v2
  targetNamespace: 7-demo
  timeout: 10s
